# version: '3.8'

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mangue/data/mariadb_data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mangue/data/wordpress_data

services:
  # 
  mariadb:
    container_name: mariadb
    env_file: .env
    networks:
    - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb    
    volumes:
    - mariadb_data:/var/lib/mysql
    restart: on-failure
    expose:
    - '3306'
  #
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress_data:/var/www/wordpress
    networks:
    - inception    
    depends_on:
    - mariadb
    build:
      context: ./requirements/wordpress    
      dockerfile: Dockerfile
    image: wordpress     
    restart: on-failure
    expose:
    - '9000'
  #
  nginx:
    container_name: nginx
    env_file: .env
    volumes:
    - wordpress_data:/var/www/wordpress
    networks:
    - inception
    depends_on:
    - wordpress    
    build:
      context: ./requirements/nginx    
      dockerfile: Dockerfile
    image: nginx
    ports:
    - '443:443'
    restart: always

networks:
  inception:
    name: inception
    driver: bridge