services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: on-failure
    expose:
      - "3306"
    env_file:
      - .env  
    volumes:
      - mariadb:/var/lib/mysql    
    networks:
      - inception    
    # - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    # healthcheck:      
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s
    #   timeout: 10s      
    # command: mysqld --innodb_force_recovery=1   
  # wordpress:
  #   container_name: wordpress
  #   build: ./requirements/wordpress      
  #   image: wordpress
  #   restart: always
  #   expose:
  #     - "9000"
  #   volumes:
  #     - wordpress:/var/www/wordpress
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - inception
  # nginx:
  #   container_name: nginx
  #   build: ./requirements/nginx
  #   image: nginx
  #   restart: always
  #   ports:
  #   - "443:443"
  #   volumes:
  #   - wordpress:/var/www/wordpress
  #   env_file:
  #   - .env    
  #   depends_on:
  #   - wordpress
  #   networks:
  #   - inception
  
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/caguillo/data/mariadb
  # wordpress:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/caguillo/data/wordpress

networks:
  inception:    
    driver: bridge