services:
  # mariadb:
  #   container_name: mariadb
  #   build: ./requirements/mariadb
  #   image: mariadb
  #   restart: on-failure
  #   expose:
  #   - '3306'
  #   volumes:
  #   - mariadb:/var/lib/mysql
  #   env_file:
  #   - .env
  #   networks:
  #   - inception      
  # wordpress:
  #   container_name: wordpress
  #   env_file: .env
  #   volumes:
  #   - wordpress:/var/www/wordpress
  #   networks:
  #   - inception    
  #   depends_on:
  #   - mariadb
  #   build:
  #     context: ./requirements/wordpress    
  #     dockerfile: Dockerfile
  #   image: wordpress     
  #   restart: on-failure
  #   expose:
  #   - '9000'  
  nginx:
    container_name: nginx
    env_file:
    - .env
    volumes:
    - wordpress:/var/www/wordpress
    # networks:
    # - inception
    # depends_on:
    # - wordpress    
    build:
      context: ./requirements/nginx    
      dockerfile: Dockerfile
    image: nginx
    ports:
    - '443:443'
    restart: always

volumes:
  # mariadb:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /home/mangue/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mangue/data/wordpress

# networks:
#   inception:
#     name: inception
#     driver: bridge