version: '3.8'

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'Users/caguillo/data/mariadb-data'
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'Users/caguillo/data/wordpress-data'

services:
  # 
  mariadb:
    container_name: mariadb
    env_file: .env
    network:
    - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception    
    volumes:
    - mariadb-data:/var/lib/mysql
    restart: on-failure
    expose:
    - '3306'
  #
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress-data:/var/www/wordpress
    network:
    - inception    
    depends_on:
    - mariadb
    build:
      context: ./requirements/nginx    
      dockerfile: Dockerfile
    image: nginx:inception     
    restart: on-failure
    expose:
    - '9000'
  #
  nginx:
    container_name: nginx
    env_file: .env
    volumes:
    - wordpress-data:/var/www/wordpress
    network:
    - inception
    depends_on:
    - wordpress
    build:
      context: ./requirements/nginx    
      dockerfile: Dockerfile
    image: nginx:inception    
    ports:
    - '443:443'
    restart: always

networks:
  inception:
    name: inception
    driver: bridge