services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: unless-stopped
    # expose:
    #   - "3306"
    env_file:
      - .env  
    volumes:
      - mariadb:/var/lib/mysql    
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress      
    image: wordpress
    restart: on-failure
    # expose:
    #   - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress      
    env_file:
      - .env    
    depends_on:
      - wordpress
      - adminer
      - static
      - vsftpd
    networks:
      - inception
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis
    restart: on-failure
    # ports:
    #   - "6379:6379"    
    env_file:
      - .env    
    depends_on:
      - wordpress      
      # - vsftpd
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception     
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer
    restart: on-failure    
    # ports:
    # - "8080:8080"       
    depends_on:
    - mariadb    
    networks:
    - inception
  vsftpd:
    container_name: vsftpd
    build: ./requirements/bonus/vsftpd
    image: vsftpd
    env_file:
      - .env
    restart: on-failure    
    ports:
      - "21:21"  # FTP control
      - "21100-21110:21100-21110" # Passive ports for data transfer
    volumes:
      - wordpress:/var/www/wordpress      
    depends_on:
      - wordpress    
    networks:
      - inception
  gftp:
    container_name: gftp
    build: ./requirements/bonus/gftp
    image: gftp
    restart: on-failure
    environment:
      - DISPLAY=${DISPLAY}
    env_file:
      - .env
    # expose:
    #   - "1000"      
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - wordpress:/var/www/wordpress            
    depends_on:
      - vsftpd
      # - wordpress      
    networks:
      - inception
  static:
    container_name: static
    build: ./requirements/bonus/static
    image: static
    restart: on-failure     
    # expose:
    #   - "2000"
    networks:
      - inception          

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mangue/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mangue/data/wordpress  

networks:
  inception:    
    driver: bridge